AllCops:
  Exclude:
    - .bundle/**/*
    - bin/**/*
    - tmp/**/*
    - script/jack_hammer
    - spec/support/schema.rb
    - lib/generators/double_entry/install/templates/**/*

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/DotPosition:
  EnforcedStyle: trailing

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/SpecialGlobalVars:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

# TODO Enable these checks and fix codes

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Metrics/AbcSize:
  Max: 47 #15

Metrics/CyclomaticComplexity:
  Max: 13 #6

Metrics/LineLength:
  Max: 185

Metrics/MethodLength:
  Max: 30 # 10

Metrics/ModuleLength:
  Max: 221 #100

Metrics/PerceivedComplexity:
  Max: 13 #7
