language: ruby
rvm:
  - 2.1.2
  - 2.0.0
  - 1.9.3
env:
  - DB=mysql
  - DB=postgres
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database double_entry_test;'
  - psql -c 'create database double_entry_test;' -U postgres
script:
  - rake spec
  - ruby script/jack_hammer -t 2000
