language: ruby
sudo: false
before_script:
  - cp spec/support/database.travis.yml spec/support/database.yml
  - mysql -e 'create database double_entry_test;'
  - psql -c 'create database double_entry_test;' -U postgres
script:
  - bundle exec rake spec
  - ruby script/jack_hammer -t 2000
matrix:
  include:
    - rvm: 2.0.0
      gemfile: spec/support/gemfiles/Gemfile.rails-4.2.x
      env: DB=mysql
    - rvm: 2.1.7
      gemfile: spec/support/gemfiles/Gemfile.rails-4.2.x
      env: DB=mysql
    - rvm: 2.2.3
      gemfile: spec/support/gemfiles/Gemfile.rails-3.2.x
      env: DB=mysql
    - rvm: 2.2.3
      gemfile: spec/support/gemfiles/Gemfile.rails-4.1.x
      env: DB=mysql
    - rvm: 2.2.3
      gemfile: spec/support/gemfiles/Gemfile.rails-4.2.x
      env: DB=mysql
    - rvm: 2.2.3
      gemfile: spec/support/gemfiles/Gemfile.rails-4.2.x
      env: DB=sqlite
    - rvm: 2.2.3
      gemfile: spec/support/gemfiles/Gemfile.rails-4.2.x
      env: DB=postgres
