language: ruby
before_script:
  - cp spec/support/database.travis.yml spec/support/database.yml
  - mysql -e 'create database double_entry_test;'
  - psql -c 'create database double_entry_test;' -U postgres
script:
  - rake spec
  - ruby script/jack_hammer -t 2000
  - rake rubocop
matrix:
  include:
    - rvm: 1.9.3
      gemfile: spec/support/gemfiles/Gemfile.rails-4.2.x
      env: DB=mysql
    - rvm: 2.0.0
      gemfile: spec/support/gemfiles/Gemfile.rails-4.2.x
      env: DB=mysql
    - rvm: 2.2.2
      gemfile: spec/support/gemfiles/Gemfile.rails-4.1.x
      env: DB=mysql
    - rvm: 2.2.2
      gemfile: spec/support/gemfiles/Gemfile.rails-4.2.x
      env: DB=mysql
    - rvm: 2.2.2
      gemfile: spec/support/gemfiles/Gemfile.rails-4.2.x
      env: DB=sqlite
    - rvm: 2.2.2
      gemfile: spec/support/gemfiles/Gemfile.rails-4.2.x
      env: DB=postgres
    - rvm: 2.1.6
      gemfile: spec/support/gemfiles/Gemfile.rails-3.2.x
      env: DB=mysql
