mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: double_entry_<%= Rails.env %>

postgres: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: double_entry_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "postgres" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
